export * from "./common";
export * from "./home";
export * from "./about";
export * from "./insurance-case";
export * from "./yur-face-page";
export * from "./mtpl-insurance";
export * from "./partner";
export * from "./politics";
export * from "./news";
export * from "./contancts"
