import { FC } from "react";
import { LayoutProps } from "./layout.t";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import { Footer } from "..";

const Layout: FC<LayoutProps> = ({ children, title }) => {
  const {t} = useTranslation();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content={t('site_meta_content')} key="title" />
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      </Head>

      <main>{children}</main>

      <Footer/>
    </>
  );
};

export default Layout;
